# Generated by Django 6.0.6 on 2026-07-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerupload",
            name="failed_records",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customerupload",
            name="file_type",
            field=models.CharField(default="unknown", max_length=10),
        ),
        migrations.AddField(
            model_name="customerupload",
            name="imported_records",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customerupload",
            name="original_file",
            field=models.FileField(
                blank=True, null=True, upload_to="customer_uploads/"
            ),
        ),
    ]
