# Generated by Django 6.0.6 on 2026-07-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_campaignchannel"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="campaigns.customerrecord",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_audience",
                "unique_together": {("campaign", "customer")},
            },
        ),
    ]
