# Generated by Django 6.0.6 on 2026-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_campaigntemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
