# Generated by Django 6.0.6 on 2026-07-05 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0010_campaign_completed_at_campaign_scheduled_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rendered_message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="campaigns.channel",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="campaigns.customerrecord",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_delivery",
                "indexes": [
                    models.Index(
                        fields=["campaign"], name="campaign_de_campaig_deb11f_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="campaign_de_custome_ce4e61_idx"
                    ),
                    models.Index(
                        fields=["status"], name="campaign_de_status_990baf_idx"
                    ),
                    models.Index(
                        fields=["channel"], name="campaign_de_channel_2b6076_idx"
                    ),
                ],
            },
        ),
    ]
