# Generated by Django 6.0.6 on 2026-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_campaigndelivery"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="campaigndelivery",
            constraint=models.UniqueConstraint(
                fields=("campaign", "customer", "channel"),
                name="unique_campaign_customer_channel",
            ),
        ),
    ]
