# Generated by Django 6.0.6 on 2026-07-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_library', '0001_initial'),
        ('campaigns', '0012_campaigndelivery_unique_campaign_customer_channel'),
        ('content_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_templates', to='asset_library.asset'),
        ),
        migrations.AddField(
            model_name='template',
            name='generated_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_templates', to='content_studio.generatedcontent'),
        ),
    ]
