# Generated by Django 6.0.6 on 2026-07-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_campaign_submitted_at_campaign_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="review_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
