# Generated by Django 6.0.6 on 2026-07-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0016_campaign_review_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigntemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_templates",
                to="campaigns.template",
            ),
        ),
    ]
