# Generated by Django 6.0.6 on 2026-07-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_campaign_started_at_db_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='customer_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiences', to='campaigns.customerupload'),
        ),
    ]
