# Generated by Django 6.0.6 on 2026-07-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_audience_optional_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
