import { Campaign } from '../types';

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_01',
    name: 'Summer Clearance Sale Blast',
    type: 'EMAIL',
    status: 'COMPLETED',
    recipientsCount: 24500,
    sentCount: 24500,
    openRate: 26.4,
    clickRate: 5.2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 29).toISOString(),
  },
  {
    id: 'camp_02',
    name: 'October Newsletter & Features Drop',
    type: 'EMAIL',
    status: 'SCHEDULED',
    recipientsCount: 48320,
    sentCount: 0,
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'camp_03',
    name: 'Flash Sale Coupon Push Alert',
    type: 'PUSH',
    status: 'COMPLETED',
    recipientsCount: 8900,
    sentCount: 8900,
    openRate: 45.1,
    clickRate: 12.8,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'camp_04',
    name: 'Product Feature Launch SMS',
    type: 'SMS',
    status: 'COMPLETED',
    recipientsCount: 15400,
    sentCount: 15400,
    openRate: 98.2, // SMS open rates are usually very high!
    clickRate: 18.5,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: 'camp_05',
    name: 'Black Friday VIP Discount WhatsApp',
    type: 'WHATSAPP',
    status: 'DRAFT',
    recipientsCount: 3200,
    sentCount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'camp_06',
    name: 'Abandoned Cart Rescue Chain',
    type: 'EMAIL',
    status: 'PUBLISHED', // Active campaign running in background
    recipientsCount: 1250,
    sentCount: 1210,
    openRate: 38.6,
    clickRate: 9.1,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
