import { Contact } from '../types';

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'con_01',
    firstName: 'Sarah',
    lastName: 'Connor',
    email: 'sarah.connor@cyberdyne.com',
    phone: '+1 (555) 901-2345',
    companyName: 'Cyberdyne Systems',
    status: 'ACTIVE',
    tags: ['Customer', 'Enterprise', 'Tech'],
    lastContactedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'con_02',
    firstName: 'John',
    lastName: 'Connor',
    email: 'john.connor@resistance.net',
    phone: '+1 (555) 302-8901',
    companyName: 'Resistance Corp',
    status: 'ACTIVE',
    tags: ['Lead', 'High Value'],
    lastContactedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 80).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'con_03',
    firstName: 'Thomas',
    lastName: 'Anderson',
    email: 'neo@matrix.io',
    phone: '+1 (555) 101-0101',
    companyName: 'Meta Cortex',
    status: 'PENDING',
    tags: ['Lead', 'Developer'],
    lastContactedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'con_04',
    firstName: 'Ellen',
    lastName: 'Ripley',
    email: 'ripley@weyland-yutani.corp',
    phone: '+1 (555) 203-4567',
    companyName: 'Weyland-Yutani',
    status: 'ACTIVE',
    tags: ['Customer', 'Churn Risk'],
    lastContactedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'con_05',
    firstName: 'Bruce',
    lastName: 'Wayne',
    email: 'bruce@wayneenterprise.com',
    phone: '+1 (555) 999-8888',
    companyName: 'Wayne Enterprises',
    status: 'INACTIVE',
    tags: ['Enterprise', 'VIP'],
    lastContactedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'con_06',
    firstName: 'Clark',
    lastName: 'Kent',
    email: 'clark.kent@dailyplanet.com',
    phone: '+1 (555) 444-5555',
    companyName: 'Daily Planet',
    status: 'ACTIVE',
    tags: ['Lead', 'Press'],
    lastContactedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'con_07',
    firstName: 'Tony',
    lastName: 'Stark',
    email: 'tony@starkindustries.com',
    phone: '+1 (555) 300-4000',
    companyName: 'Stark Industries',
    status: 'ACTIVE',
    tags: ['Customer', 'VIP', 'Tech'],
    lastContactedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 150).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
