# Generated by Django 6.0.6 on 2026-07-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0013_remove_user_company'),
        ('asset_library', '0004_alter_assettag_unique_together_remove_asset_company_and_more'),
        ('billing', '0002_remove_wallet_company'),
        ('communications', '0003_remove_communicationevent_communicati_organiz_9b5bcd_idx_and_more'),
        ('content_studio', '0004_remove_brandvoice_company_and_more'),
        ('events', '0002_remove_websiteevent_website_eve_organiz_d63e22_idx_and_more'),
        ('integrations', '0002_alter_integrationprovider_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
