import { Company } from '../types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp_01',
    name: 'Cyberdyne Systems',
    industry: 'Robotics & AI',
    domain: 'cyberdyne.com',
    employeesCount: 2500,
    annualRevenue: 450000000,
    contactsCount: 15,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp_02',
    name: 'Wayne Enterprises',
    industry: 'Defense & Tech',
    domain: 'wayneenterprise.com',
    employeesCount: 12000,
    annualRevenue: 2800000000,
    contactsCount: 42,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 300).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp_03',
    name: 'Stark Industries',
    industry: 'Defense & Energy',
    domain: 'starkindustries.com',
    employeesCount: 9500,
    annualRevenue: 1500000000,
    contactsCount: 38,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 250).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp_04',
    name: 'Weyland-Yutani Corp',
    industry: 'Aerospace & Colonization',
    domain: 'weyland-yutani.corp',
    employeesCount: 45000,
    annualRevenue: 8900000000,
    contactsCount: 29,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 400).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp_05',
    name: 'Tyrell Corporation',
    industry: 'Biotech & Robotics',
    domain: 'tyrell.com',
    employeesCount: 1500,
    annualRevenue: 350000000,
    contactsCount: 8,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
