# Generated by Django 6.0.6 on 2026-07-07 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('EMAIL', 'Email'), ('BLOG', 'Blog'), ('AD_COPY', 'Ad Copy'), ('SOCIAL', 'Social Media'), ('CAPTION', 'Caption')], db_index=True, max_length=20)),
                ('platform', models.CharField(choices=[('NONE', 'None'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)')], db_index=True, default='NONE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='common.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('prompt', models.TextField()),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('generated_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content_studio.generatedcontent')),
            ],
            options={
                'db_table': 'content_versions',
                'ordering': ['-version_number'],
                'unique_together': {('generated_content', 'version_number')},
            },
        ),
    ]
