# Generated by Django 6.0.6 on 2026-07-15 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('content_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandVoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tone', models.CharField(default='Professional', help_text='e.g., Professional, Casual, Humorous', max_length=100)),
                ('target_audience', models.TextField(blank=True, help_text='Describe the target audience')),
                ('guidelines', models.TextField(blank=True, help_text="Specific rules, do's and don'ts")),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_voice', to='common.company')),
            ],
            options={
                'db_table': 'brand_voices',
            },
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prompt_template', models.TextField(help_text='Use {{variables}} for dynamic injection')),
                ('content_type', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('BLOG', 'Blog'), ('AD_COPY', 'Ad Copy'), ('SOCIAL', 'Social Media'), ('CAPTION', 'Caption')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_templates', to='common.company')),
            ],
            options={
                'db_table': 'content_templates',
                'ordering': ['name'],
            },
        ),
    ]
