# Generated by Django 6.0.6 on 2026-07-15 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_library', '0003_remove_asset_file_alter_asset_file_url'),
        ('common', '0001_initial'),
        ('content_studio', '0002_brandvoice_contenttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_prompt', models.TextField(blank=True)),
                ('enhanced_prompt', models.TextField(blank=True)),
                ('workflow_state', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_drafts', to='common.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_campaign_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reviews', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='content_studio.contentdraft')),
            ],
            options={
                'db_table': 'content_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)')], max_length=20)),
                ('image_size', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('approval_status', models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('published_datetime', models.DateTimeField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='content_studio.contentdraft')),
            ],
            options={
                'db_table': 'content_draft_platforms',
                'unique_together': {('draft', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption_text', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=255)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caption', to='content_studio.contentplatform')),
            ],
            options={
                'db_table': 'content_captions',
            },
        ),
        migrations.CreateModel(
            name='ImageReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_images', to='asset_library.asset')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content_studio.contentplatform')),
            ],
            options={
                'db_table': 'content_image_references',
            },
        ),
        migrations.CreateModel(
            name='ContentDraftVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('enhanced_prompt_snapshot', models.TextField(blank=True)),
                ('regeneration_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions_created', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content_studio.contentdraft')),
            ],
            options={
                'db_table': 'content_draft_versions',
                'ordering': ['-version_number'],
                'unique_together': {('draft', 'version_number')},
            },
        ),
    ]
