# Generated by Django 6.0.6 on 2026-07-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0003_contentdraft_approval_contentplatform_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandvoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contentdraft',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contenttemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='company',
        ),
        migrations.AlterModelTable(
            name='contentdraft',
            table='content_draft_drafts',
        ),
    ]
