# Generated by Django 6.0.6 on 2026-07-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0004_remove_brandvoice_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandvoice',
            name='brand_description',
            field=models.TextField(blank=True, help_text='What does your brand do?'),
        ),
        migrations.AddField(
            model_name='brandvoice',
            name='call_to_action',
            field=models.TextField(blank=True, help_text='What action should your social media posts encourage?'),
        ),
        migrations.AddField(
            model_name='brandvoice',
            name='content_pillars',
            field=models.TextField(blank=True, help_text='What topics should your content focus on?'),
        ),
        migrations.AddField(
            model_name='brandvoice',
            name='unique_value',
            field=models.TextField(blank=True, help_text='What makes your brand different from competitors?'),
        ),
        migrations.AlterField(
            model_name='brandvoice',
            name='guidelines',
            field=models.TextField(blank=True, help_text='Are there any words, phrases, or styles the AI should always use or avoid?'),
        ),
        migrations.AlterField(
            model_name='brandvoice',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Who is your target audience?'),
        ),
        migrations.AlterField(
            model_name='brandvoice',
            name='tone',
            field=models.CharField(default='Professional', help_text='How do you want your brand to sound on social media?', max_length=255),
        ),
    ]
