# Generated by Codex on 2026-07-06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_name", models.CharField(choices=[("PAGE_VISITED", "Page Visited"), ("BUTTON_CLICKED", "Button Clicked"), ("LINK_CLICKED", "Link Clicked"), ("PRODUCT_VIEWED", "Product Viewed"), ("CART_ABANDONED", "Cart Abandoned"), ("CHECKOUT_STARTED", "Checkout Started"), ("CHECKOUT_COMPLETED", "Checkout Completed")], db_index=True, max_length=100)),
                ("user_identifier", models.CharField(db_index=True, max_length=255)),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("url", models.CharField(blank=True, max_length=2048)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="website_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "website_event",
            },
        ),
        migrations.AddIndex(
            model_name="websiteevent",
            index=models.Index(fields=["organization", "event_name"], name="website_eve_organiz_d63e22_idx"),
        ),
        migrations.AddIndex(
            model_name="websiteevent",
            index=models.Index(fields=["organization", "user_identifier"], name="website_eve_organiz_44dded_idx"),
        ),
        migrations.AddIndex(
            model_name="websiteevent",
            index=models.Index(fields=["created_at"], name="website_eve_created_0332c1_idx"),
        ),
    ]
