# Generated by Django 6.0.6 on 2026-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='websiteevent',
            name='website_eve_organiz_d63e22_idx',
        ),
        migrations.RemoveIndex(
            model_name='websiteevent',
            name='website_eve_organiz_44dded_idx',
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(fields=['event_name'], name='website_eve_event_n_072942_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(fields=['user_identifier'], name='website_eve_user_id_54e06b_idx'),
        ),
        migrations.RemoveField(
            model_name='websiteevent',
            name='organization',
        ),
    ]
