# Generated by Django 6.0.6 on 2026-07-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='company',
        ),
    ]
