"use client";

import { useQueries } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { BarChart3, CalendarDays, CheckCircle2, Download, Instagram, Megaphone, Send, UsersRound } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useState } from "react";
import { apiClient, parseApiError } from "@/services/api-client";
import { superAdminService } from "@/services/super-admin.service";

type Platform = { platform: string; status: string; approval_status: string; scheduled_datetime: string|null; published_datetime: string|null };
type Draft = { id:string; workflow_state:string; platforms:Platform[]; created_at:string };
type Campaign = { id:number; campaign_name:string; status:string; contacts:number; sent:number; delivered:number; opened:number; clicked:number; created_at:string };
type CampaignResponse = { count:number; results:Campaign[] };

export function AdminAnalytics(){
  const [socialPlatform,setSocialPlatform]=useState("INSTAGRAM");
  const [campaignChannel,setCampaignChannel]=useState("EMAIL");
  const [analytics,dashboard,draftsQuery,campaignsQuery]=useQueries({queries:[
    {queryKey:["admin-analytics"],queryFn:superAdminService.analytics},
    {queryKey:["admin-dashboard"],queryFn:superAdminService.dashboard},
    {queryKey:["analytics-social-drafts"],queryFn:async()=>(await apiClient.get<Draft[]>("/api/content/content-drafts/")).data},
    {queryKey:["analytics-campaigns"],queryFn:async()=>(await apiClient.get<CampaignResponse>("/api/campaigns/my/",{params:{page_size:100}})).data},
  ]});
  const loading=[analytics,dashboard,draftsQuery,campaignsQuery].some((query)=>query.isLoading);
  const error=[analytics,dashboard,draftsQuery,campaignsQuery].find((query)=>query.error)?.error;
  if(loading)return <div className="space-y-5"><div className="h-20 animate-pulse rounded-2xl bg-white"/><div className="grid gap-4 lg:grid-cols-2"><div className="h-[760px] animate-pulse rounded-2xl bg-white"/><div className="h-[760px] animate-pulse rounded-2xl bg-white"/></div></div>;
  if(error)return <div className="sa-card p-10 text-red-600">{parseApiError(error)}</div>;
  const drafts=draftsQuery.data??[];const campaigns=campaignsQuery.data?.results??[];const platformRows=drafts.flatMap((draft)=>draft.platforms.map((platform)=>({draft,platform})));const socialRows=platformRows.filter(({platform})=>platform.platform===socialPlatform);
  const published=socialRows.filter(({platform})=>platform.status==="POSTED").length;const scheduled=socialRows.filter(({platform})=>platform.scheduled_datetime&&platform.status!=="POSTED").length;const pending=socialRows.filter(({draft})=>draft.workflow_state==="IN_REVIEW").length;
  const completed=campaigns.filter((campaign)=>campaign.status==="COMPLETED").length;const active=campaigns.filter((campaign)=>["SENDING","SCHEDULED","APPROVED"].includes(campaign.status)).length;
  const socialSeries=lastSevenDays().map((day)=>({day:day.label,published:socialRows.filter(({platform})=>sameDay(platform.published_datetime,day.date)).length,scheduled:socialRows.filter(({platform})=>sameDay(platform.scheduled_datetime,day.date)).length}));
  const campaignSeries=campaigns.slice(0,7).reverse().map((campaign)=>({name:compactTitle(campaign.campaign_name),sent:campaign.sent,delivered:campaign.delivered,opened:campaign.opened,clicked:campaign.clicked}));
  const leadSeries=campaigns.slice(0,7).reverse().map((campaign)=>({name:new Date(campaign.created_at).toLocaleDateString("en-US",{month:"short",day:"numeric"}),contacts:campaign.contacts}));
  const socialCards=[["Published",published,Send,"text-blue-600"],["Scheduled",scheduled,CalendarDays,"text-orange-500"],["Social Posts",socialRows.length,Instagram,"text-pink-600"],["Pending",pending,UsersRound,"text-emerald-600"]] as const;
  const campaignCards=[["All Campaigns",campaignsQuery.data?.count??0,Megaphone],["Active",active,Send],["Completed",completed,CheckCircle2],["Leads Generated",campaigns.reduce((sum,item)=>sum+item.contacts,0),UsersRound]] as const;
  const channelStats=campaignChannel==="WHATSAPP"?[analytics.data?.whatsapp.sent??0,analytics.data?.whatsapp.read_rate??0,analytics.data?.whatsapp.reply_rate??0,"Read rate","Reply rate"]:campaignChannel==="SMS"?[analytics.data?.sms.sent??0,analytics.data?.sms.delivery_rate??0,dashboard.data?.deliveries.success_rate??0,"Delivery rate","Success rate"]:[analytics.data?.email.sent??0,analytics.data?.email.open_rate??0,analytics.data?.email.click_rate??0,"Open rate","Click rate"];
  function exportCsv(){const rows=[["Campaign","Status","Contacts","Sent","Delivered","Opened","Clicked"],...campaigns.map((c)=>[c.campaign_name,c.status,c.contacts,c.sent,c.delivered,c.opened,c.clicked])];const blob=new Blob([rows.map((row)=>row.join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="marketing-analytics.csv";anchor.click();URL.revokeObjectURL(url);}
  return <div><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="sa-title normal-case">Analytics</h1><p className="sa-subtitle">Track performance across social media and campaigns.</p></div><div className="flex gap-2"><span className="secondary-button flex min-h-11 items-center gap-2 px-4"><CalendarDays size={16}/>Last 7 days</span><button aria-label="Export analytics" className="secondary-button grid min-h-11 place-items-center px-4" onClick={exportCsv}><Download size={17}/></button></div></div>
    <div className="grid items-start gap-4 xl:grid-cols-2"><motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="sa-card overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="text-sm font-black uppercase tracking-wide">Social Media</h2><div className="mt-4 flex gap-7 text-xs font-bold text-slate-600">{[["INSTAGRAM","Instagram"],["X","X (Twitter)"],["FACEBOOK","Facebook"],["LINKEDIN","LinkedIn"]].map(([value,label])=><button className={socialPlatform===value?"border-b-2 border-blue-500 pb-3 text-blue-600":"pb-3"} key={value} onClick={()=>setSocialPlatform(value)}>{label}</button>)}</div></div><div className="grid grid-cols-2 divide-x divide-slate-100 border-b border-slate-100 md:grid-cols-4">{socialCards.map(([label,value,Icon,tone])=><div className="p-5" key={label}><div className="flex items-center gap-2 text-xs font-bold text-slate-600"><Icon className={tone} size={17}/>{label}</div><strong className="mt-3 block text-2xl">{compact(value)}</strong><span className="mt-2 block text-[10px] text-emerald-600">Live content data</span></div>)}</div><div className="grid gap-3 p-4 lg:grid-cols-2"><ChartCard title="Published" data={socialSeries} dataKey="published" color="#2563eb"/><ChartCard title="Scheduled" data={socialSeries} dataKey="scheduled" color="#16a34a"/></div><div className="border-t border-slate-100 p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-black">Social Media Activity Calendar</h3><span className="text-xs text-slate-500">Posts per day</span></div><MiniCalendar rows={socialRows}/></div></motion.section>
      <motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="sa-card overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="text-sm font-black uppercase tracking-wide">Campaigns</h2><div className="mt-4 flex gap-8 text-xs font-bold text-slate-600">{[["EMAIL","Email"],["WHATSAPP","WhatsApp"],["SMS","SMS"]].map(([value,label])=><button className={campaignChannel===value?"border-b-2 border-blue-500 pb-3 text-blue-600":"pb-3"} key={value} onClick={()=>setCampaignChannel(value)}>{label}</button>)}</div></div><div className="grid grid-cols-2 divide-x divide-slate-100 border-b border-slate-100 md:grid-cols-4">{campaignCards.map(([label,value,Icon])=><div className="p-5" key={label}><div className="flex items-center gap-2 text-xs font-bold text-slate-600"><Icon className="text-blue-600" size={17}/>{label}</div><strong className="mt-3 block text-2xl">{compact(Number(value))}</strong><span className="mt-2 block text-[10px] text-emerald-600">Recorded activity</span></div>)}</div><div className="p-5"><h3 className="mb-4 font-black">Campaign Performance</h3><div className="h-64">{campaignSeries.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={campaignSeries}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={10}/><YAxis fontSize={10}/><Tooltip/><Legend/><Bar dataKey="sent" fill="#111827"/><Bar dataKey="delivered" fill="#64748b"/><Bar dataKey="opened" fill="#cbd5e1"/><Bar dataKey="clicked" fill="#ef4444"/></BarChart></ResponsiveContainer>:<EmptyChart/>}</div></div><div className="border-t border-slate-100 p-5"><h3 className="mb-4 font-black">Lead Growth</h3><div className="h-64">{leadSeries.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={leadSeries}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={10}/><YAxis fontSize={10}/><Tooltip/><Line type="monotone" dataKey="contacts" stroke="#8b5cf6" strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer>:<EmptyChart/>}</div></div><div className="grid grid-cols-3 border-t border-slate-100 bg-slate-50 p-4 text-center text-xs"><div><b className="block text-lg">{compact(Number(channelStats[0]))}</b>{campaignChannel.toLowerCase()} sent</div><div><b className="block text-lg">{channelStats[1]}%</b>{channelStats[3]}</div><div><b className="block text-lg">{channelStats[2]}%</b>{channelStats[4]}</div></div></motion.section></div></div>;
}
function ChartCard({title,data,dataKey,color}:{title:string;data:Array<Record<string,string|number>>;dataKey:string;color:string}){return <div className="rounded-xl border border-slate-100 p-3"><div className="mb-2 flex justify-between"><b className="text-sm">{title}</b><span className="text-[10px] text-slate-400">Last 7 days</span></div><div className="h-40"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" fontSize={9}/><YAxis fontSize={9} allowDecimals={false}/><Tooltip/><Line type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2.5} dot={{r:2}}/></LineChart></ResponsiveContainer></div></div>}
function MiniCalendar({rows}:{rows:Array<{draft:Draft;platform:Platform}>}){const now=new Date();const first=new Date(now.getFullYear(),now.getMonth(),1);return <div><div className="grid grid-cols-7 text-center text-[10px] font-bold text-slate-500">{["S","M","T","W","T","F","S"].map((day,index)=><span key={`${day}${index}`}>{day}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-1">{Array.from({length:35},(_,index)=>{const date=new Date(first);date.setDate(index-first.getDay()+1);const count=rows.filter(({platform,draft})=>sameDay(platform.published_datetime||platform.scheduled_datetime||draft.created_at,date)).length;return <div className={`rounded-lg p-2 text-center text-xs ${date.toDateString()===now.toDateString()?"bg-blue-600 text-white":count?"bg-blue-50 text-blue-700":"text-slate-500"}`} key={date.toISOString()}><span>{date.getDate()}</span>{count>0&&<b className="mt-1 block text-[9px]">{count}</b>}</div>})}</div></div>}
function EmptyChart(){return <div className="grid h-full place-items-center text-center text-slate-400"><div><BarChart3 className="mx-auto"/><p className="mt-2 text-sm">No recorded activity yet</p></div></div>}
function lastSevenDays(){return Array.from({length:7},(_,index)=>{const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()-(6-index));return{date,label:date.toLocaleDateString("en-US",{weekday:"short"})};});}
function sameDay(value:string|null|undefined,date:Date){return !!value&&new Date(value).toDateString()===date.toDateString();}
function compact(value:number){return Intl.NumberFormat("en",{notation:value>=1000?"compact":"standard",maximumFractionDigits:1}).format(value);}
function compactTitle(value:string){return value.length>11?`${value.slice(0,10)}…`:value;}
