"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Filter, List, Pencil, Plus, Search, Tags, Trash2, Upload, X } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { apiClient, parseApiError } from "@/services/api-client";

type RecordRow={id:number;data:Record<string,unknown>;created_at:string};
type Contact={name:string;email:string;tags:string[];list:string;score:number;status:string;activity:string};
const blank:Contact={name:"",email:"",tags:[],list:"General",score:50,status:"Active",activity:"Just added"};
const value=(data:Record<string,unknown>,keys:string[],fallback="")=>{for(const key of keys){const found=data[key];if(found!==undefined&&found!==null&&String(found).trim())return String(found)}return fallback};
const normalize=(row:RecordRow):Contact=>{const rawTags=row.data.tags;return {name:value(row.data,["name","full_name","Name","Full Name"],"Unnamed contact"),email:value(row.data,["email","Email","email_address"]),tags:Array.isArray(rawTags)?rawTags.map(String):value(row.data,["tags","Tags"]).split(",").map(x=>x.trim()).filter(Boolean),list:value(row.data,["list","List","segment"],"General"),score:Number(value(row.data,["score","Score"],"0"))||0,status:value(row.data,["status","Status"],"Active"),activity:value(row.data,["activity","Activity"],"Imported contact")}};

export function AdminContacts(){
  const client=useQueryClient(); const fileRef=useRef<HTMLInputElement>(null);
  const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState("All"); const [listFilter,setListFilter]=useState("All");
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState<number|null>(null); const [form,setForm]=useState<Contact>(blank);
  const query=useQuery({queryKey:["admin-contacts"],queryFn:async()=>(await apiClient.get<RecordRow[]>("/api/customers/")).data});
  const rows=query.data??[];
  const contacts=useMemo(()=>rows.map(row=>({row,contact:normalize(row)})).filter(({contact})=>{const q=search.toLowerCase();return (!q||contact.name.toLowerCase().includes(q)||contact.email.toLowerCase().includes(q))&&(statusFilter==="All"||contact.status===statusFilter)&&(listFilter==="All"||contact.list===listFilter)}),[rows,search,statusFilter,listFilter]);
  const lists=Array.from(new Set(rows.map(r=>normalize(r).list).filter(Boolean)));
  const save=useMutation({mutationFn:()=>editing?apiClient.patch(`/api/customers/${editing}/`,form):apiClient.post("/api/customers/",form),onSuccess:()=>{toast.success(editing?"Contact updated":"Contact added");setOpen(false);setEditing(null);setForm(blank);void client.invalidateQueries({queryKey:["admin-contacts"]})},onError:e=>toast.error(parseApiError(e))});
  const remove=useMutation({mutationFn:(id:number)=>apiClient.delete(`/api/customers/${id}/`),onSuccess:()=>{toast.success("Contact deleted");void client.invalidateQueries({queryKey:["admin-contacts"]})},onError:e=>toast.error(parseApiError(e))});
  const importFile=async(file?:File)=>{if(!file)return;const body=new FormData();body.append("file",file);try{await apiClient.post("/api/customers/uploads/",body);toast.success("Contacts imported");void client.invalidateQueries({queryKey:["admin-contacts"]})}catch(e){toast.error(parseApiError(e))}finally{if(fileRef.current)fileRef.current.value=""}};
  const exportCsv=()=>{const header=["Name","Email","Tags","List","Score","Status","Activity"];const lines=rows.map(r=>{const c=normalize(r);return [c.name,c.email,c.tags.join(";"),c.list,c.score,c.status,c.activity].map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")});const blob=new Blob([[header.join(","),...lines].join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="contacts.csv";a.click();URL.revokeObjectURL(url)};
  const beginEdit=(row:RecordRow)=>{setEditing(row.id);setForm(normalize(row));setOpen(true)};
  const beginAdd=()=>{setEditing(null);setForm(blank);setOpen(true)};

  return <div><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><span className="inline-flex rounded-full bg-blue-50 px-3 py-1 text-[10px] font-extrabold uppercase tracking-[.2em] text-blue-600">Audience workspace</span><h1 className="sa-title mt-3">CONTACTS</h1><p className="sa-subtitle">{rows.length} contacts</p></div><div className="flex flex-wrap gap-2"><input ref={fileRef} className="hidden" type="file" accept=".csv,.xlsx,.xls" onChange={e=>void importFile(e.target.files?.[0])}/><button className="secondary-button flex items-center gap-2" onClick={()=>fileRef.current?.click()}><Upload size={17}/>Import</button><button className="secondary-button flex items-center gap-2" disabled={!rows.length} onClick={exportCsv}><Download size={17}/>Export</button><button className="primary-button" onClick={beginAdd}><Plus size={18}/>Add Contact</button></div></div>
    <section className="sa-card overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 bg-slate-50/70 p-5"><label className="relative min-w-64 flex-1"><Search className="absolute left-4 top-3.5 text-slate-400" size={18}/><input className="h-12 w-full rounded-xl border border-slate-200 bg-white pl-11 pr-4 outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-100" placeholder="Search contacts…" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className={`secondary-button flex items-center gap-2 ${statusFilter!=="All"?"!border-blue-300 !text-blue-600":""}`} onClick={()=>setStatusFilter(v=>v==="All"?"Active":v==="Active"?"Inactive":"All")}><Filter size={17}/>Filter: {statusFilter}</button><button className="secondary-button flex items-center gap-2" onClick={()=>toast.info("Tags are shown on every contact row")}><Tags size={17}/>Tags</button><select aria-label="Filter by list" className="h-11 rounded-xl border border-slate-200 bg-white px-3 font-semibold text-slate-700" value={listFilter} onChange={e=>setListFilter(e.target.value)}><option>All</option>{lists.map(item=><option key={item}>{item}</option>)}</select><List size={17} className="text-slate-400"/></div>
      {query.isLoading?<div className="space-y-3 p-5">{[1,2,3,4].map(i=><div className="h-16 animate-pulse rounded-xl bg-slate-100" key={i}/>)}</div>:query.isError?<div className="p-12 text-center text-red-600">{parseApiError(query.error)}</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-[.12em] text-slate-500"><tr><th className="px-5 py-4">Name</th><th>Email</th><th>Tags</th><th>List</th><th>Score</th><th>Status</th><th>Activity</th><th>Actions</th></tr></thead><tbody>{contacts.map(({row,contact},i)=><tr className="border-t border-slate-100 transition hover:bg-blue-50/35" key={row.id}><td className="px-5 py-4 font-bold text-slate-900">{contact.name}</td><td className="text-slate-600">{contact.email||"—"}</td><td><div className="flex gap-1">{contact.tags.length?contact.tags.map(tag=><span className="rounded-full bg-slate-100 px-2 py-1 text-xs" key={tag}>{tag}</span>):<span className="text-slate-400">—</span>}</div></td><td className="text-slate-600">{contact.list}</td><td><div className="flex items-center gap-2"><span className="h-1.5 w-14 overflow-hidden rounded-full bg-slate-100"><span className="block h-full rounded-full bg-gradient-to-r from-blue-500 to-violet-500" style={{width:`${Math.min(100,contact.score)}%`}}/></span><small>{contact.score}</small></div></td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${contact.status==="Active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{contact.status}</span></td><td className="text-xs text-slate-500">{contact.activity}</td><td><div className="flex gap-1"><button className="icon-button" title="Edit contact" onClick={()=>beginEdit(row)}><Pencil size={16}/></button><button className="icon-button text-red-500" title="Delete contact" onClick={()=>{if(confirm(`Delete ${contact.name}?`))remove.mutate(row.id)}}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{!contacts.length&&<div className="p-12 text-center text-slate-500">No contacts match your filters.</div>}</div>}
    </section>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/65 p-4 backdrop-blur-sm"><form className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl" onSubmit={e=>{e.preventDefault();save.mutate()}}><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">{editing?"Edit":"Add"} contact</h2><p className="text-sm text-slate-500">Store contact details in your audience database.</p></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="field sm:col-span-2"><span>Name *</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field sm:col-span-2"><span>Email *</span><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field"><span>List</span><input value={form.list} onChange={e=>setForm({...form,list:e.target.value})}/></label><label className="field"><span>Tags</span><input placeholder="VIP, SaaS" value={form.tags.join(", ")} onChange={e=>setForm({...form,tags:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label className="field"><span>Score</span><input min={0} max={100} type="number" value={form.score} onChange={e=>setForm({...form,score:Number(e.target.value)})}/></label><label className="field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></select></label><button className="primary-button sm:col-span-2" disabled={save.isPending}>{save.isPending?"Saving…":editing?"Save changes":"Add contact"}</button></div></form></div>}
  </div>;
}
