# Generated by Codex on 2026-07-06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("secret", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "webhook_event",
            },
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["secret", "processed"], name="webhook_eve_secret_b40d12_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["created_at"], name="webhook_eve_created_9addbf_idx"),
        ),
    ]
