# Generated by Django 6.0.6 on 2026-07-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_company_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetotp",
            name="otp",
            field=models.CharField(max_length=255),
        ),
    ]
