# Generated by Django 6.0.6 on 2026-07-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_company_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauser',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to='accounts.mauser'),
        ),
    ]
