# Generated by Django 6.0.6 on 2026-07-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_mauser_managed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRequest',
        ),
    ]
