# Generated by Django 6.0.6 on 2026-07-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_passwordresetotp_otp_delete_accessrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresetotp",
            name="user",
        ),

        migrations.DeleteModel(
            name="PasswordResetOTP",
        ),
    ]
