# Generated by Django 6.0.6 on 2026-07-14 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_passwordresetotp_user_delete_accessrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mauser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ma_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
