# Generated by Django 6.0.6 on 2026-07-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_mauser_user_delete_accessrequest"),
    ]

    operations = [
    ]
