# Generated by Django 6.0.6 on 2026-07-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_accessrequest'),
        ('accounts', '0011_delete_accessrequest'),
    ]

    operations = [
    ]
