# Generated by Django 6.0.6 on 2026-07-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_backfill_recent_user_first_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauser',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text="If True, the user's content must be approved before publishing."),
        ),
    ]
