# Generated by Django 6.0.6 on 2026-07-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_campaignaudience"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="audience_definition",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="customer_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="campaigns.customerupload",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
