# Generated by Django 6.0.6 on 2026-07-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_audience"),
        ("tasks", "0002_task_audience_definition_task_customer_upload_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="audience_definition",
        ),
        migrations.RemoveField(
            model_name="task",
            name="customer_upload",
        ),
        migrations.AddField(
            model_name="task",
            name="audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="campaigns.audience",
            ),
        ),
    ]
