# Generated by Django 6.0.6 on 2026-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0010_campaign_completed_at_campaign_scheduled_at_and_more"),
        ("tasks", "0003_remove_task_audience_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="channels",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="campaigns.channel"
            ),
        ),
    ]
