# Generated by Django 6.0.6 on 2026-07-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0013_template_asset_template_generated_content"),
        ("tasks", "0004_task_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="audience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="campaigns.audience",
            ),
        ),
    ]
