# Generated by Django 6.0.6 on 2026-07-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0017_alter_campaigntemplate_template"),
        ("tasks", "0006_task_last_activity_at_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="audience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="campaigns.audience",
            ),
        ),
    ]
