# Generated by Django 6.0.6 on 2026-07-02 05:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automation')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation_execution',
            },
        ),
        migrations.CreateModel(
            name='AutomationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('EXECUTE', 'Execute'), ('ADMIN', 'Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='automation.automation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_automations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automation_member',
            },
        ),
        migrations.CreateModel(
            name='AutomationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('TRIGGER', 'Trigger'), ('CONDITION', 'Condition'), ('ACTION', 'Action'), ('UTILITY', 'Utility')], db_index=True, max_length=30)),
                ('action_name', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('business_config', models.JSONField(blank=True, default=dict)),
                ('ui_config', models.JSONField(blank=True, default=dict)),
                ('execution_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='automation.automation')),
            ],
            options={
                'db_table': 'automation_node',
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationexecution')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationnode')),
            ],
            options={
                'db_table': 'automation_execution_log',
            },
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.automationnode'),
        ),
        migrations.CreateModel(
            name='AutomationEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(default='DEFAULT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='automation.automation')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='automation.automationnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='automation.automationnode')),
            ],
            options={
                'db_table': 'automation_edge',
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['owner'], name='automation_owner_i_67a13d_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['status'], name='automation_status_6ac0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['created_at'], name='automation_created_33c65b_idx'),
        ),
        migrations.AddIndex(
            model_name='automationmember',
            index=models.Index(fields=['automation'], name='automation__automat_97931c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationmember',
            index=models.Index(fields=['user'], name='automation__user_id_16d628_idx'),
        ),
        migrations.AddIndex(
            model_name='automationmember',
            index=models.Index(fields=['permission'], name='automation__permiss_194b13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automationmember',
            unique_together={('automation', 'user')},
        ),
        migrations.AddIndex(
            model_name='automationnode',
            index=models.Index(fields=['automation'], name='automation__automat_f55a51_idx'),
        ),
        migrations.AddIndex(
            model_name='automationnode',
            index=models.Index(fields=['node_type'], name='automation__node_ty_38eaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='automationnode',
            index=models.Index(fields=['action_name'], name='automation__action__dbd189_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['execution'], name='automation__executi_2c7015_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['node'], name='automation__node_id_769588_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['status'], name='automation__status_e34e45_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['automation'], name='automation__automat_771444_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['status'], name='automation__status_b9a358_idx'),
        ),
        migrations.AddIndex(
            model_name='automationedge',
            index=models.Index(fields=['automation'], name='automation__automat_c87188_idx'),
        ),
        migrations.AddIndex(
            model_name='automationedge',
            index=models.Index(fields=['source_node'], name='automation__source__e4d1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='automationedge',
            index=models.Index(fields=['target_node'], name='automation__target__44bbda_idx'),
        ),
    ]
