# Generated by Django 6.0.6 on 2026-07-01 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(default='DEFAULT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'automation_edge',
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'automation_execution',
            },
        ),
        migrations.CreateModel(
            name='AutomationExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'automation_execution_log',
            },
        ),
        migrations.CreateModel(
            name='AutomationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('EXECUTE', 'Execute'), ('ADMIN', 'Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'automation_member',
            },
        ),
        migrations.CreateModel(
            name='AutomationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('TRIGGER', 'Trigger'), ('CONDITION', 'Condition'), ('ACTION', 'Action'), ('UTILITY', 'Utility')], db_index=True, max_length=30)),
                ('action_name', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('business_config', models.JSONField(blank=True, default=dict)),
                ('ui_config', models.JSONField(blank=True, default=dict)),
                ('execution_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automation_node',
            },
        ),
        migrations.AddField(
            model_name='automation',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automation',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='automation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_automations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['created_at'], name='automation_created_33c65b_idx'),
        ),
        migrations.AddField(
            model_name='automationedge',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='automation.automation'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automation'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationexecution'),
        ),
        migrations.AddField(
            model_name='automationmember',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='automation.automation'),
        ),
        migrations.AddField(
            model_name='automationmember',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_automations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationnode',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='automation.automation'),
        ),
        migrations.AddField(
            model_name='automationexecutionlog',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationnode'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.automationnode'),
        ),
        migrations.AddField(
            model_name='automationedge',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='automation.automationnode'),
        ),
        migrations.AddField(
            model_name='automationedge',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='automation.automationnode'),
        ),
        migrations.AddIndex(
            model_name='automationmember',
            index=models.Index(fields=['automation'], name='automation__automat_97931c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationmember',
            index=models.Index(fields=['user'], name='automation__user_id_16d628_idx'),
        ),
        migrations.AddIndex(
            model_name='automationmember',
            index=models.Index(fields=['permission'], name='automation__permiss_194b13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automationmember',
            unique_together={('automation', 'user')},
        ),
        migrations.AddIndex(
            model_name='automationnode',
            index=models.Index(fields=['automation'], name='automation__automat_f55a51_idx'),
        ),
        migrations.AddIndex(
            model_name='automationnode',
            index=models.Index(fields=['node_type'], name='automation__node_ty_38eaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='automationnode',
            index=models.Index(fields=['action_name'], name='automation__action__dbd189_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['execution'], name='automation__executi_2c7015_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['node'], name='automation__node_id_769588_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecutionlog',
            index=models.Index(fields=['status'], name='automation__status_e34e45_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['automation'], name='automation__automat_771444_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['status'], name='automation__status_b9a358_idx'),
        ),
        migrations.AddIndex(
            model_name='automationedge',
            index=models.Index(fields=['automation'], name='automation__automat_c87188_idx'),
        ),
        migrations.AddIndex(
            model_name='automationedge',
            index=models.Index(fields=['source_node'], name='automation__source__e4d1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='automationedge',
            index=models.Index(fields=['target_node'], name='automation__target__44bbda_idx'),
        ),
    ]
