# Generated by Django 6.0.6 on 2026-07-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationedge_automationexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationexecution',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='resume_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='retry_after',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='automationexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('RETRYING', 'Retrying'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['status', 'resume_at'], name='automation__status_8c7772_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['status', 'retry_after'], name='automation__status_e3537d_idx'),
        ),
    ]
