# Generated by Django 6.0.6 on 2026-07-07 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('OPENAI', 'OpenAI'), ('AWS_S3', 'AWS S3'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)')], db_index=True, max_length=20)),
                ('credentials', models.JSONField(default=dict, help_text='Store API keys, secrets, or OAuth tokens here')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='common.company')),
            ],
            options={
                'db_table': 'integration_providers',
                'unique_together': {('company', 'provider_type')},
            },
        ),
    ]
