# Generated by Django 6.0.6 on 2026-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integrationprovider',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='integrationprovider',
            name='provider_type',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('AWS_S3', 'AWS S3'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)')], db_index=True, max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='integrationprovider',
            name='company',
        ),
    ]
