# Generated by Django 6.0.6 on 2026-07-22 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_mauser_requires_approval'),
        ('integrations', '0002_alter_integrationprovider_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)')], db_index=True, max_length=20)),
                ('platform_account_id', models.CharField(help_text='ID on the external platform', max_length=255)),
                ('account_name', models.CharField(help_text='Display name (e.g. Page Name, Handle)', max_length=255)),
                ('encrypted_access_token', models.TextField()),
                ('encrypted_refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('ERROR', 'Error')], default='CONNECTED', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Platform-specific data (e.g. scopes, profile picture URL, page details)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to='accounts.mauser')),
            ],
            options={
                'db_table': 'integration_social_connections',
                'unique_together': {('user', 'platform', 'platform_account_id')},
            },
        ),
    ]
