# Generated by Django 6.0.6 on 2026-07-22 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_socialconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_id', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)')], max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('external_post_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to='integrations.socialconnection')),
            ],
            options={
                'db_table': 'integration_publish_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
