# Generated by Django

from django.db import migrations
import logging

logger = logging.getLogger(__name__)

def migrate_social_connections(apps, schema_editor):
    SocialConnection = apps.get_model('integrations', 'SocialConnection')
    MAUser = apps.get_model('accounts', 'MAUser')

    connections = SocialConnection.objects.all()
    migrated_count = 0

    for connection in connections:
        ma_user = connection.user
        
        # We need to simulate get_tenant_owner_profile logic
        # - If user is SUPER_ADMIN or ADMIN, returns their MAUser profile.
        # - If user is USER, returns their managing ADMIN's MAUser profile.
        
        if ma_user and ma_user.role == "USER" and ma_user.managed_by_id:
            # Found a connection owned by a USER. We must move it to their ADMIN.
            admin_user = ma_user.managed_by
            logger.info(f"Migrating SocialConnection {connection.id} from USER {ma_user.id} to ADMIN {admin_user.id}")
            connection.user = admin_user
            connection.save(update_fields=['user'])
            migrated_count += 1
            
    print(f"\\nSuccessfully migrated {migrated_count} SocialConnections to tenant roots.")

def reverse_migrate_social_connections(apps, schema_editor):
    # This migration is a data correction and cannot be perfectly reversed
    # without knowing the original user, but we can just leave it as is 
    # since it moves ownership to the correct hierarchy level.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_publishlog'),
        ('accounts', '0008_mauser_managed_by'), # Ensure MAUser is loaded
    ]

    operations = [
        migrations.RunPython(migrate_social_connections, reverse_migrate_social_connections),
    ]
