# Generated by Django 6.0.6 on 2026-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
