# Generated by Django 6.0.6 on 2026-07-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_library', '0002_asset_file_alter_asset_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='file',
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_url',
            field=models.URLField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
