# Generated by Django 6.0.6 on 2026-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_library', '0003_remove_asset_file_alter_asset_file_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assettag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='assetfolder',
            unique_together={('parent', 'name')},
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='If True, only the uploaded_by user can view this.'),
        ),
        migrations.RemoveField(
            model_name='assettag',
            name='company',
        ),
        migrations.RemoveField(
            model_name='assetfolder',
            name='company',
        ),
    ]
