# Generated by Codex on 2026-07-06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automation", "0003_automationexecution_paused_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationEmailProvider",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("SMTP", "SMTP"), ("AWS_SES", "Amazon SES")], default="SMTP", max_length=50)),
                ("aws_access_key", models.CharField(blank=True, max_length=255)),
                ("aws_secret_key", models.CharField(blank=True, max_length=255)),
                ("aws_region", models.CharField(blank=True, max_length=100)),
                ("verified_domain", models.CharField(blank=True, max_length=255)),
                ("daily_limit", models.PositiveIntegerField(default=0)),
                ("monthly_limit", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="email_providers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "organization_email_provider",
            },
        ),
        migrations.CreateModel(
            name="CommunicationEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("WHATSAPP", "WhatsApp"), ("NOTIFICATION", "Notification")], db_index=True, max_length=30)),
                ("event_name", models.CharField(db_index=True, max_length=100)),
                ("recipient", models.CharField(db_index=True, max_length=255)),
                ("status", models.CharField(choices=[("SENT", "Sent"), ("DELIVERED", "Delivered"), ("OPENED", "Opened"), ("CLICKED", "Clicked"), ("READ", "Read"), ("REPLIED", "Replied"), ("BOUNCED", "Bounced"), ("UNSUBSCRIBED", "Unsubscribed"), ("FAILED", "Failed")], db_index=True, max_length=30)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("execution", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="communication_events", to="automation.automationexecution")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="communication_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "communication_event",
            },
        ),
        migrations.AddIndex(
            model_name="organizationemailprovider",
            index=models.Index(fields=["organization", "is_active"], name="organizatio_organiz_7f5f76_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationemailprovider",
            index=models.Index(fields=["provider"], name="organizatio_provide_17f674_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationevent",
            index=models.Index(fields=["organization", "channel", "status"], name="communicati_organiz_9b5bcd_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationevent",
            index=models.Index(fields=["event_name"], name="communicati_event_n_3eb28e_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationevent",
            index=models.Index(fields=["created_at"], name="communicati_created_2f1cfa_idx"),
        ),
    ]
