# Generated by Django 6.0.6 on 2026-07-07 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaigndelivery_unique_campaign_customer_channel'),
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_events', to='campaigns.campaign'),
        ),
        migrations.CreateModel(
            name='OrganizationPushProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('FCM', 'Firebase Cloud Messaging'), ('VAPID', 'Web Push (VAPID)')], default='FCM', max_length=50)),
                ('server_key', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_push_provider',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_f8b44d_idx'), models.Index(fields=['provider'], name='organizatio_provide_834c35_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSMSProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MSG91', 'MSG91')], default='MSG91', max_length=50)),
                ('auth_key', models.CharField(blank=True, max_length=255)),
                ('sender_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_sms_provider',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_aba2ac_idx'), models.Index(fields=['provider'], name='organizatio_provide_fa1afd_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationWhatsAppProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('META', 'Meta WhatsApp Business Platform')], default='META', max_length=50)),
                ('access_token', models.CharField(blank=True, max_length=500)),
                ('phone_number_id', models.CharField(blank=True, max_length=100)),
                ('business_account_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_whatsapp_provider',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_3d3bf9_idx'), models.Index(fields=['provider'], name='organizatio_provide_098536_idx')],
            },
        ),
    ]
