# Generated by Django 6.0.6 on 2026-07-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_automationexecution_paused_at_and_more'),
        ('campaigns', '0015_campaign_submitted_at_campaign_submitted_by'),
        ('communications', '0002_communicationevent_campaign_organizationpushprovider_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communicationevent',
            name='communicati_organiz_9b5bcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationemailprovider',
            name='organizatio_organiz_7f5f76_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationpushprovider',
            name='organizatio_organiz_f8b44d_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationsmsprovider',
            name='organizatio_organiz_aba2ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationwhatsappprovider',
            name='organizatio_organiz_3d3bf9_idx',
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['channel', 'status'], name='communicati_channel_0ac3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationemailprovider',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_882146_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationpushprovider',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_19de2e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsmsprovider',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_2fa14c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationwhatsappprovider',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_7a69dd_idx'),
        ),
        migrations.RemoveField(
            model_name='communicationevent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationemailprovider',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationpushprovider',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationsmsprovider',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationwhatsappprovider',
            name='organization',
        ),
    ]
